# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add Two Numbers
#'
#' Return the sum of two numbers.
#' @param x, a double number
#' @param y, a double number
#' @export
add_cpp <- function(x, y) {
    .Call(`_pkgrcpp_add_cpp`, x, y)
}

approx_pi <- function(N) {
    .Call(`_pkgrcpp_approx_pi`, N)
}

approx_pi_dqrng <- function(N) {
    .Call(`_pkgrcpp_approx_pi_dqrng`, N)
}

#' Sum over a vector
#'
#' Return the sum of all the elements in the vector.
#' @param vec, a vector of arbitrary length.
#' @export
sumC <- function(vec) {
    .Call(`_pkgrcpp_sumC`, vec)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call(`_pkgrcpp_RcppExport_registerCCallable`)
})
