# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add Two Numbers
#'
#' Return the sum of two numbers.
#' @param x
#' @param y
#' @export
add_cpp <- function(x, y) {
    .Call('_pkgrcpp_add_cpp', PACKAGE = 'pkgrcpp', x, y)
}

#' Sum over a vector
#'
#' Return the sum of all the elements in the vector.
#' @param vec, a vector of arbitrary length.
#' @export
sumC <- function(vec) {
    .Call('_pkgrcpp_sumC', PACKAGE = 'pkgrcpp', vec)
}

